### ISSUE TITLE
[1.7.10] Matmos 35.4.6 crash,35.4.5 no crash

### ISSUE THREAD

**Issue by quentin452** [makamys/MAtmos#25] opened 2022-09-04 04:39 UTC
Matmos 35.4.6 crash when make a world

Mods list :

SpongeMixins-1.5.0
mixingasm-1.7.10-v0.2.3
matmos-1.7.10-35.4.6

35.4.6 log : 

https://paste.ee/p/sjlah

**Comment by makamys** [comment] 2022-09-04 17:21
Duplicate of #24

**Closed as not planned by makamys** 2022-09-04 17:21 UTC
