### ISSUE TITLE
NullPointerException in IDDealiaser with SereneSeasons

### ISSUE THREAD

**Issue by SkySem** [makamys/MAtmos#14] opened 2021-03-19 10:18 UTC
Game version: 1.7.10 
forge version: 10.13.4.1614

On version 1.7.10, someone good person, port mod serene seasons to 1.7.10 (and this is great !!) *[Link](https://www.curseforge.com/minecraft/mc-mods/serene-seasons/files/all?filter-game-version=1738749986%3A5)*

When starting the game, everything works fine, and without questions, but when you try to enter the world (no matter, server or single game) together with a mod MAtmos, and a mod SereneSeasons
you get a crash : [link](https://pastebin.com/gGk5akS8)

**Comment by facetorched** [comment] 2021-05-19 06:37
I also get this crash. but it happens for no reason sometimes when joining a server

**Comment by makamys** [comment] 2021-07-29 07:49
I can't reproduce this. What's the smallest set of mods this happens with? Does it happen when you create a new world? What about superflat? Are you sure it's caused by Serene Seasons?

**Comment by makamys** [comment] 2021-07-29 21:15
I changed something that might have fixed this, if not then the next time it happens we'll have a bit more data to work with.

**Comment by ppk-gh** [comment] 2021-09-20 18:33
Managed to reproduce the same crash with [this](https://www.curseforge.com/minecraft/mc-mods/gregtech-4) port of Gregtech 4.

[pastebin](https://pastebin.com/7ricu8Kn)

Could consistently reproduce the crash on a new instance with only IC2 experimental, GT and NEI installed.

**Comment by makamys** [comment] 2021-09-22 03:16
Thanks. I forgot to mention it here, but I also managed to reproduce it with Et Futurum Requiem 2.2.1 recently, where it only happens when raw ores are disabled in the config (as reported by *KibaTheBarbarian*).

**Comment by makamys** [comment] 2021-11-07 14:56
Closing as fixed in 35.4.2.2.

**Closed as completed by makamys** 2021-11-07 14:56 UTC
