### ISSUE TITLE
[1.7.10] TFC+ error

### ISSUE THREAD

**Issue by facetorched** [makamys/MAtmos#10] opened 2021-01-14 20:34 UTC
MAtmos works great with TFC+ but every time i join the game I get an error message. It doesn't seem to affect the ability for MAtmos to function but the chat spam is annoying. Here's the error message it gives me:

[https://pastebin.com/7LHcMkG5](https://pastebin.com/7LHcMkG5)

**Comment by facetorched** [comment] 2021-02-16 19:44
@makamys just wondering if you are still supporting this!

**Comment by makamys** [comment] 2021-07-29 00:19
This looks like a bug in TFC+, you might wanna tell Dunk about it. I added a quick fix that should make MAtmos not crash when it happens.

**Comment by facetorched** [comment] 2021-07-29 01:35
But is this illegal cast unlikely to happen normally? Not sure what's going on but since it only happens with MAtmos I assume it's not something that is normally expected to happen.

Anyways, I will send it to dunk.

**Comment by makamys** [comment] 2021-07-29 01:46
Well, I'm not sure what's happening, but all MAtmos is doing to trigger it is calling the `getCollisionBoundingBoxFromPool` method of the `com.dunk.tfc.Blocks.BlockSlab` class. I don't think I'm doing anything unreasonable here.
https://github.com/makamys/MAtmos/blob/2887c892890eb5bf6af3e4d39fe6160859722cd1/src/main/java/eu/ha3/matmos/data/scanners/ScanAir.java#L288-L290
I'd need to do some testing to know for sure though, I'll look into it later.

**Comment by facetorched** [comment] 2021-07-29 01:56
I think you might be right. It's likely that dunk (or probably bioxx) when coding the chiseled blocks didn't think anyone would ever want to call that method on the block and overlooked something. (I think wood construct is chiseled blocks or maybe lumber)

**Comment by makamys** [comment] 2021-07-29 12:03
Actually, I can't reproduce this myself. I tried chiseling blocks into slabs, but no crash happens; the code in `BlockSlab` runs successfully. What blocks cause it?

**Comment by facetorched** [comment] 2021-07-29 17:45
Try detailed chiseled blocks or placed lumber blocks

**Comment by facetorched** [comment] 2021-07-29 17:46
Also dunk added a check in the code so it won't cause an issue in the next release of TFC+ anyway

**Comment by makamys** [comment] 2021-07-29 21:11
> Try detailed chiseled blocks or placed lumber blocks

That's what I tried, but no problems.  (TFC+ 0.87.0, MAtmos 1.7.10-35.4.1)

> Also dunk added a check in the code 

Cool! Guess I can close this then.

**Closed as completed by makamys** 2021-07-29 21:11 UTC
